spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopingcart?createDatabaseIfNotExist=true
    username: root
    password: Pravin@69
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

websiteUrl: http://localhost:5173